# Site settings
title: Pet Delivery Dujeong
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pet-delivery-cheonan.kro.kr/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: dog_cat.jpg
hero-title: 펫딜 두정점
hero-description: "10월 22일 OPEN"

roy-insta-img: roy_insta.png
natto-insta-img: natto_insta.png

# Location
location-title: 찾아오는길
location-address: 충청남도 천안시 서북구 봉정로 324, 제근린생활동 104호(두정동, 두정역 효성해링턴 플레이스)

# Author - Creator
author-name: Ben Campbell
author-image: 10.jpg
about-author: My name is Ben Campbell. I'm an actor and a musician. Retro wolf banjo succulen tsgoch ujang tumeric hammock offal.
author-email: help.example@gmail.com
author-twitter: https://twitter.com/
author-facebook: https://twitter.com/
author-instagram: https://www.instagram.com/
author-roy-insta: https://www.instagram.com/roy.12.01/
author-natto-insta: https://www.instagram.com/natto__lim/
author-pinterest: https://pinterest.com/
author-kakao_opentalk: https://open.kakao.com/o/gO8UkPGe

# Other Authors - here you can add Other authors. For example Natali_Braxton
authors:
  Natali_Braxton:
    author-name: Natali Braxton
    author-image: 111.jpg
    about-author: My name is Natali Braxton. I love walking, I play the guitar in my spare time. And also write articles about different technologies.
    author-email: natali.example@gmail.com
    author-twitter: https://twitter.com/
    author-facebook: https://twitter.com/
    author-instagram: https://www.instagram.com/
    author-roy-insta: https://www.instagram.com/roy.12.01/
    author-natto-insta: https://www.instagram.com/natto__lim/
    author-pinterest: https://pinterest.com/

# Social Media Links (Links are located in hero and footer)
twitter: https://twitter.com/
facebook: https://facebook.com/
google-plus: https://plus.google.com/
instagram: https://www.instagram.com/
roy-instagram: https://www.instagram.com/roy.12.01/
natto-instagram: https://www.instagram.com/natto__lim/
pinterest: https://pinterest.com/
youtube: https://www.youtube.com/
kakao_opentalk: https://open.kakao.com/o/gO8UkPGe

# Contact Form Settings
contact-subtitle: Pok pok listicle meggings, gluten-free deep v you probably haven't heard of them taxidermy iPhone gentrify seitan. Kogi cornhole enamel. # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
